### ISSUE TITLE
Elasticsearch 7.12

### ISSUE THREAD

**Issue by lsmilek1** [jrots/skiplist-elastic-plugin#1]
Hi,

I am trying to install your plugin, but I get following error:

> -> Installing https://github.com/jrots/skiplist-elastic-plugin/blob/master/build/distributions/skiplist-plugin-6.2.2-SNAPSHOT.zip?raw=true
> -> Downloading https://github.com/jrots/skiplist-elastic-plugin/blob/master/build/distributions/skiplist-plugin-6.2.2-SNAPSHOT.zip?raw=true
> [=================================================] 100%   
> -> Failed installing https://github.com/jrots/skiplist-elastic-plugin/blob/master/build/distributions/skiplist-plugin-6.2.2-SNAPSHOT.zip?raw=true
> -> Rolling back https://github.com/jrots/skiplist-elastic-plugin/blob/master/build/distributions/skiplist-plugin-6.2.2-SNAPSHOT.zip?raw=true
> -> Rolled back https://github.com/jrots/skiplist-elastic-plugin/blob/master/build/distributions/skiplist-plugin-6.2.2-SNAPSHOT.zip?raw=true
> ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

Is your plugin still actual for version 7.12? Thank you!

**Comment by lsmilek1** [comment]
I tried to unzip the package and remove the "elasticsearch" folder so that jar files are directly in the zip and I get following error:

> Exception in thread "main" java.io.FileNotFoundException:  (No such file or directory)
> 	at java.base/java.io.FileInputStream.open0(Native Method)
> 	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
> 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
> 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
> 	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
> 	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
> 	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:440)
> 	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:321)
> 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:242)
> 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
> 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
> 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
> 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
> 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
> 	at org.elasticsearch.cli.Command.main(Command.java:79)
> 	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)
>

**Comment by dadoonet** [comment]
@mvSapphire Could you help on that?
